name: Build and Deploy MonoGame.Framework.WindowsDX

on:
  workflow_dispatch:

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Disable annotations
        run: echo "::remove-matcher owner=csc::"

      - name: Install required workloads
        run:   |
              if [ "$RUNNER_OS" == "Linux" ]; then
                    echo "MICROSOFT SUPPORT ANDROID WORKLOAD ON LINUX PLZZZ!"
              elif [ "$RUNNER_OS" == "Windows" ]; then
                    dotnet.exe workload install android ios macos
              else
                    dotnet workload install android ios macos
              fi
        shell: bash

      - name: Build MonoGame.Framework.WindowsDX
        run: dotnet build --configuration Release ./MonoGame.Framework.WindowsDX.sln

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Upload Artifacts
        run: dotnet pack --configuration Release --output ./nupkg ./MonoGame.Framework.WindowsDX.sln
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RUNTIME_URL: "${{ env.ACTIONS_RUNTIME_URL }}"

  deploy:
      name: Deploy
      needs: [ build ]
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'push' }}
      permissions:
          packages: write
          contents: write
      steps:
          - name: Clone Repository
            uses: actions/checkout@v4

          - name: Setup .NET ${{ matrix.dotnet-version }}
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '8.0.x'

          - name: Expose GitHub Runtime
            uses: crazy-max/ghaction-github-runtime@v3

          - name: Push GitHub NuGets
            run: dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Publish to nuget.org
            run: dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
            env:
              NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
